version: '3.8'

services:
  infra-postgres:
    image: debezium/postgres:15
    container_name: infra-postgres
    environment:
      POSTGRES_DB: yarmaq_accounts
      POSTGRES_USER: danial
      POSTGRES_PASSWORD: yarmaq_pass
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "wal_level=logical"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U danial -d yarmaq_accounts"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zitadel

  kafka:
    # Используем проверенный Confluent образ
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      # Разделяем внутренний трафик (для UI) и внешний (для твоего кода)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Важно для KRaft режима (без Zookeeper)
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zitadel

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: yarmaq
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - zitadel
  
  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      kafka-topics --create --if-not-exists --topic transaction.created --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --if-not-exists --topic account.created --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --if-not-exists --topic account.balance.updated --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --if-not-exists --topic district.critical --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 &&
      echo 'Topics created successfully'
      "
    networks:
      - zitadel
      
networks:
  zitadel:
    external: true